### ISSUE TITLE
Remove `no-ternary` rule

### ISSUE THREAD

**Issue by JoaoHenriquePereira** [seegno/eslint-config-seegno#12]
I believe we all understand the arguments against using ternaries such as:

* Usage for overly complex logic.
* Usage with nested ternaries.
* It can easily be replaced with a simple `if`.

However I do believe that using ternaries can promote readibility and most importantly the final decision is up to the reviewing team which is often 2 people.

The strict restriction is a bit of an *overkill* in my opinion. I suggest we keep the rules `no-nested-ternary` and `no-unneeded-ternary` as it indeed does limit the usage of the ternary operator.

**Comment by pgom** [comment]
:+1:

**Comment by brunnolou** [comment]
:+1:

**Comment by fixe** [comment]
+1.

**Comment by nunofgs** [comment]
:+1: if we keep the `no-nested-ternary` and `no-unneeded-ternary` rules.

**Comment by ruiquelhas** [comment]
:+1:
