### ISSUE TITLE
Remove `eslint` dependency

### ISSUE THREAD

**Issue by ruiquelhas** [seegno/eslint-config-seegno#2]
`eslint` is currently required as a dependency because it's being used as a linter for the module itself since it has additional code to load the rules declared in yaml.

If the rules are expressed in a regular Node.js™ module using `module.exports` and the proper main file path in `package.json`, the dependency is no longer needed.

**Comment by ruimarinho** [comment]
:+1: for this. We should look into the maintainers own config - https://www.npmjs.com/package/eslint-config-eslint.
