### ISSUE TITLE
Atom interprets `async` as error

### ISSUE THREAD

**Issue by ricardogama** [seegno/eslint-config-seegno#3]
Although the `eslint` bin does not complain, the `async` keyword is currently being interpreted as a violation of the `generator-star-spacing` rule on the [AtomLinter/linter-eslint plugin](https://github.com/AtomLinter/linter-eslint):

```js
async function foo() {
  await bar();
}
```

```
error  Unexpected space after *  generator-star-spacing
```

However, if I use the `eslint:recommended` extension and keep the `babel-eslint` as parser on `.eslintrc`, no error appears:

```yml
extends: 'eslint:recommended'
parser: 'babel-eslint'
```

Anyone else got this issue? I can always disable this rule on the `.eslintrc`, but since it works fine without this extension maybe it can be related with some configuration. 

Nice job with this module btw!

**Comment by ruiquelhas** [comment]
It seems to be a [known issue](https://github.com/babel/babel-eslint#known-issues) on `babel-eslint` and we are enforcing `generator-star-spacing: 2` in the rules. We are thinking about changing that specific rule, but for now I recommend you override it in your own configuration.

I'll keep the issue open until then though. Thanks!
