### ISSUE TITLE
Consider using other sort-imports rule

### ISSUE THREAD

**Issue by joaogranado** [seegno/eslint-config-seegno#43]
Current `sort-imports` implementation is quite odd. IMO it should check for `ImportDefaultSpecifier` specifier. Currently everything looks out of place, since it can enforces single imports order, even for named imports.

Example:

```js
import { A, b } from 'module-a';
import B from 'module-b';
import { c } from 'module-c'
import d from './module-d' 
```

It would make more sense if defaults and named were grouped together such as:

```js
import { A, b } from 'module-a';
import { c } from 'module-c';
import B from 'module-b';
import d from './module-d';
```

There is a [plugin](https://github.com/wyze/eslint-plugin-wyze) that is implemented this way, and there are some discussions [here](https://github.com/eslint/eslint/issues/5311) and [here](https://github.com/eslint/eslint/issues/5305) in order to update this rule.

**Comment by nunorafaelrocha** [comment]
100% agree! +1

**Comment by ricardogama** [comment]
+1

**Comment by joaonice** [comment]
+1

**Comment by ricardogama** [comment]
Since by eslint/eslint#5311there's no prospects of changing this rule, I suggest to revive this discussion. 

It would be great to add a plugin such as [eslint-plugin-sort-imports-es6](https://github.com/erikdesjardins/eslint-plugin-sort-imports-es6) or [eslint-plugin-wyze](https://github.com/wyze/eslint-plugin-wyze) and make import sorting not such a headache.

@ruimarinho @rplopes Any thoughts on this?

**Comment by ruimarinho** [comment]
Tbh, I really don't care about the actual sorting algorithm as long as it is consistent and stable (and it is). Reaching a consensus on which algorithm is better is always going to be a source of distraction and using the bundled version has the advantage of continued maintenance. However, to be clear, I don't oppose adding a plugin to change the current behaviour if that is something that the majority prefers.

**Comment by rplopes** [comment]
I don't have any strong views on any alternative. Both sound god enough to me. If people prefer the suggested approach (judging by this issue's feedback so far), then IMO we can go for it.

**Comment by nunorafaelrocha** [comment]
I would like to have a sorting algorithm like the one suggested by @joaogranado. If the solution is to add a plugin, I'm voting for that.

**Comment by rplopes** [comment]
Cool. I can review and marge a PR that implements that.
