### ISSUE TITLE
Require parenthesis for arrow functions

### ISSUE THREAD

**Issue by pgom** [seegno/eslint-config-seegno#6]
Allowing parenthesis on arrow functions with only one argument would make the arrow function declaration more consistent. Therefore, setting the `arrow-parens`  flag to `always` would be ideal for this case.

**Comment by ricardogama** [comment]
+1

**Comment by ruiquelhas** [comment]
I'm not sure about this. The rule itself implies consistency for that specific case. It's mostly a matter of taste than anything else. Anyway, I'm totally open to change it if there are more "complaints".

**Comment by pgom** [comment]
@ruiquelhas, it's totally a matter of taste and I can live with both possibilities. On my opinion, it's better to force the paren for that case to be clear when an arrow function is being used (no matter the number of arguments are used).

**Comment by fixe** [comment]
-1 but we need more votes :-)

**Comment by promag** [comment]
Why the exception with 1 argument only when even with no arguments there has to be parenthesis? For me it would be:

````js
singleParam => { statements } // NOT ALLOWED
singleParam => expression // ALLOWED
singleParam => ({foo: bar}) // ALLOWED
```

**Comment by JoaoHenriquePereira** [comment]
0 arguments: ()
1 argument: arg
2+ arguments: (arg1,arg2...)

Always found this rule a bit weird even though I have to confess in some cases it looks a bit better. 

+1

**Comment by ruiquelhas** [comment]
I gave it a second thought and, if the argument is consistency, I'm actually +1 on this if we do the same for the statement part (enforce the use of curly braces).

**Comment by ruipenso** [comment]
+1

**Comment by joaogranado** [comment]
I think this discussion is quite similar to semicolon vs no-semicolon. You can use both (despite the fact the latest is discouraged because it might lead to some "dangerous" side-effects) but it is all about consistency. Definitely, missing semicolons is not a feature, it is only accepted by the compiler. Personally I don't like not using parenthesis, but it is actually a feature, I as far as I'm aware it doesn't introduce any side-effect and the community is using it a lot. @JoaoHenriquePereira +1.

**Comment by pgom** [comment]
@ruimarinho, @nunofgs, @franciscocardoso more opinions on this, so we can close it and move on? :)

**Comment by ruiquelhas** [comment]
After some thought, I've changed my mind on this. +1

**Comment by pgom** [comment]
I believe we've reached a consensus :+1:  @ruiquelhas can you create a PR for it?

**Comment by franciscocardoso** [comment]
+1

**Comment by nunofgs** [comment]
:+1:

**Comment by fixe** [comment]
For the record, I prefer [airbnb's standard](https://github.com/airbnb/javascript#8.1).

```js
// good
[1, 2, 3].map(x => x * x);

// good
[1, 2, 3].reduce((y, x) => x + y);
```

**Comment by ruiquelhas** [comment]
It looks fine when it is a one-liner, otherwise I would say it becomes a little bit nasty. And having rules to cover all those cases it's overkill IMHO. So I'm thinking about just removing the requirement.

**Comment by ruimarinho** [comment]
+1 for readability. Having extra parentheses for single arguments' arrow functions is just clutter IMHO. And unlike semicolons, which are also optional in JS, it does not have any downside.

**Comment by ruimarinho** [comment]
It's 2016 so I think it's time to review this decision 😄 even babel removes parentheses for single arguments! /cc @ruiquelhas @fixe

**Comment by pgom** [comment]
@ruimarinho since make you happy is a 2016 resolution for me, you can drop this :smile:

**Comment by promag** [comment]
:oh god why:
