### ISSUE TITLE
Fix deprecation notices with `eslint-plugin-babel@4.0.0`

### ISSUE THREAD

**Issue by nunofgs** [seegno/eslint-config-seegno#65]
After upgrading to `eslint-plugin-babel@4.0.0` I noticed that eslint now throws the following deprecation notices.

```
The babel/arrow-parens rule is deprecated. Please use the built in arrow-parens rule instead.
The babel/generator-star-spacing rule is deprecated. Please use the built in generator-star-spacing rule instead.
```

Two things come to mind:

1. Should we be declaring `eslint-plugin-babel@3.x` as a peer dependency?
2. Or, should we state the version that we need in the README?

**Comment by rplopes** [comment]
Resolved by https://github.com/seegno/eslint-config-seegno/pull/66.
