### ISSUE TITLE
Remove `mocha` env

### ISSUE THREAD

**Issue by ricardogama** [seegno/eslint-config-seegno#71]
As Jest probably becoming the preferred test framework, we should consider to remove `mocha` from `env`, and perhaps the `mocha/no-exclusive-tests` rule as well.

Adding `jest` and `jasmine` to `env` can also be discussed, but IMO the test environment should be defined in each project making this preset agnostic in that concern.

**Comment by ruimarinho** [comment]
I'm also inclined for that. However, what's the disadvantage of having `mocha` and `jest` enabled?

**Comment by ricardogama** [comment]
There would be globals that are not linted and do not exist, although it doesn't seem much of a problem, actually most of the globals are shared by both frameworks.

I think we should go forward by adding those to `env` instead.

Here are the [mocha](https://github.com/sindresorhus/globals/blob/master/globals.json#L880), [jest](https://github.com/sindresorhus/globals/blob/master/globals.json#L922) and [jasmine](https://github.com/sindresorhus/globals/blob/master/globals.json#L902) globals for reference.

**Comment by ruimarinho** [comment]
For me it's fine I guess. ping @nunofgs @fixe.
